version: "3.8"

services:
  customers-db:
    image: postgres:15
    container_name: products-db
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

volumes:
  products_data: