spring:
  application:
    name: product-service

  config:
    import: optional:file:./.env[.properties]


  datasource:
    url: ${DB_PRODUCTS_URL}
    username: ${DB_PRODUCTS_USERNAME}
    password: ${DB_PRODUCTS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
